"""add_lease_relationship_to_payments

Revision ID: 1cd292d280d9
Revises: 2ebe5681041d
Create Date: 2026-04-23 18:54:36.532562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd292d280d9'
down_revision: Union[str, Sequence[str], None] = '2ebe5681041d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('lease_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'payments', 'leases', ['lease_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'lease_id')
    # ### end Alembic commands ###
