import React, { useState, useEffect } from 'react';
import { paymentsApi } from '../services/api';
import { useAuth } from '../context/AuthContext';
import './PaymentModal.css'; // Reusing modal styles

const PaymentReceipt = ({ isOpen, onClose, request }) => {
  const { isOwner } = useAuth();
  const [payment, setPayment] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (isOpen && request) {
      const fetchPayment = async () => {
        setLoading(true);
        try {
          const data = isOwner 
            ? await paymentsApi.getByRequest(request.id)
            : await paymentsApi.getTenantByRequest(request.id);
          setPayment(data);
        } catch (err) {
          console.error('Failed to fetch payment receipt:', err);
          setError('No payment record found for this lease.');
        } finally {
          setLoading(false);
        }
      };

      fetchPayment();
    }
  }, [isOpen, request, isOwner]);

  if (!isOpen) return null;

  const getStatusBadge = (status) => {
    switch (status) {
      case 'SUCCESS':
      case 'PAID': return <span className="badge badge-success">COMPLETED</span>;
      case 'INITIATED':
      case 'PENDING': return <span className="badge badge-warning">PROCESSING</span>;
      case 'FAILED': return <span className="badge badge-danger">FAILED</span>;
      default: return <span className="badge">{status}</span>;
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="modal-overlay">
      <div className="modal-content payment-modal animate-slide-up no-print-modal">
        <div className="modal-header">
          <div className="header-text">
            <h2>Payment Receipt</h2>
            <p className="text-muted text-sm">{request.property_title}</p>
          </div>
          <button className="close-btn" onClick={onClose}>&times;</button>
        </div>

        <div className="receipt-body m-top-4 print-only-receipt">
          {loading ? (
             <div className="flex-center p-4">
               <div className="spinner"></div>
             </div>
          ) : error || !payment ? (
            <div className="text-center p-4">
               <div className="text-muted m-bottom-2">📄</div>
               <p>{error || "No payment record found."}</p>
            </div>
          ) : (
            <div className="receipt-details">
              <div className="receipt-row">
                <span className="label">Amount Paid</span>
                <span className="value primary">৳ {payment.amount.toLocaleString()}</span>
              </div>
              <div className="receipt-row">
                <span className="label">Status</span>
                <span className="value">{getStatusBadge(payment.status)}</span>
              </div>
              <div className="receipt-row">
                <span className="label">Payment Method</span>
                <span className="value">{payment.method}</span>
              </div>
              
              {payment.transaction_id && (
                <div className="receipt-row">
                  <span className="label">Transaction ID</span>
                  <span className="value text-secondary">{payment.transaction_id}</span>
                </div>
              )}

              {payment.provider_reference && (
                <div className="receipt-row">
                  <span className="label">Provider Ref</span>
                  <span className="value text-secondary text-xs">{payment.provider_reference}</span>
                </div>
              )}

              {payment.reference && !payment.transaction_id && (
                <div className="receipt-row">
                  <span className="label">Reference</span>
                  <span className="value">{payment.reference}</span>
                </div>
              )}
              
              <div className="receipt-footer m-top-5 text-center text-muted text-xs">
                <p>Digital Receipt generated by RentWise Platform.</p>
                <p>Date: {new Date(payment.created_at).toLocaleDateString()}</p>
              </div>
            </div>
          )}
        </div>

        <div className="modal-footer m-top-4">
          {payment && (
            <button className="btn btn-secondary w-full m-bottom-2" onClick={handlePrint}>Print / Download</button>
          )}
          <button className="btn btn-outline-primary w-full" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
};

export default PaymentReceipt;
