import React, { useState, useEffect } from 'react';
import { paymentsApi } from '../../shared/services/api';
import { useAuth } from '../auth/AuthContext';
import './PaymentModal.css'; // Reusing modal styles

const PaymentReceipt = ({ request }) => {
  const { isOwner } = useAuth();
  const [payment, setPayment] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (request && request.id) {
      const fetchPayment = async () => {
        setLoading(true);
        try {
          const data = isOwner 
            ? await paymentsApi.getByRequest(request.id)
            : await paymentsApi.getTenantByRequest(request.id);
          setPayment(data);
        } catch (err) {
          console.error("Failed to fetch payment:", err);
          setError("No payment record found.");
        } finally {
          setLoading(false);
        }
      };
      
      fetchPayment();
    }
  }, [request, isOwner]);

  const getStatusBadge = (status) => {
    switch(status) {
      case 'PAID': return <span className="badge badge-success">PAID</span>;
      case 'INITIATED':
      case 'PENDING': return <span className="badge badge-warning">PROCESSING</span>;
      case 'FAILED': return <span className="badge badge-danger">FAILED</span>;
      default: return <span className="badge">{status}</span>;
    }
  };

  if (!request) return null;

  return (
    <div className="payment-receipt-widget glass-panel p-4">
      <div className="receipt-header flex-between">
        <h3>Digital Receipt</h3>
        <button className="btn btn-sm btn-outline no-print" onClick={() => window.print()}>
          Print PDF
        </button>
      </div>

      <div className="receipt-body m-top-4 print-only-receipt">
        {loading ? (
          <div className="flex-center p-4">
            <div className="spinner"></div>
          </div>
        ) : error || !payment ? (
          <div className="text-center p-4">
            <div className="text-muted m-bottom-2">📄</div>
            <p>{error || "No payment record found."}</p>
          </div>
        ) : (
          <div className="receipt-details">
            <div className="receipt-row">
              <span className="label">Status</span>
              <span className="value">{getStatusBadge(payment.status)}</span>
            </div>
            <div className="receipt-row">
              <span className="label">Property</span>
              <span className="value">{request.property_title || 'Unknown Property'}</span>
            </div>
            <div className="receipt-row">
              <span className="label">Tenant</span>
              <span className="value">{request.tenant_name}</span>
            </div>
            <div className="receipt-row">
              <span className="label">Amount Paid</span>
              <span className="value font-bold">৳ {payment.amount?.toLocaleString() || '0'}</span>
            </div>
            <div className="receipt-row">
              <span className="label">Payment Method</span>
              <span className="value">{payment.method}</span>
            </div>
            
            {payment.transaction_id && (
              <div className="receipt-row">
                <span className="label">Transaction ID</span>
                <span className="value text-xs">{payment.transaction_id}</span>
              </div>
            )}

            {payment.reference && (
              <div className="receipt-row">
                <span className="label">Reference</span>
                <span className="value">{payment.reference}</span>
              </div>
            )}
            
            <div className="receipt-footer m-top-5 text-center text-muted text-xs">
              <p>Digital Receipt generated by RentWise Platform.</p>
              <p>Date: {new Date(payment.created_at).toLocaleDateString()}</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default PaymentReceipt;
